name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: SAFETY MEASURES AT WORKSHOP
      id: safety-measures-at-workshop
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SAFETY-MEASURES-AT-WORKSHOP_RESULTS: "${{steps.safety-measures-at-workshop.outputs.result}}"
      with:
        runners: safety-measures-at-workshop
